// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8841dfc744bce6b2d3e075f7ace25c0c1e664c17/webpack-merge/index.d.ts
declare module "webpack-merge" {
    import {Configuration} from "webpack";

    interface WebpackMerge {
        /**
         * Merge multiple webpack configurations into one.
         */
        (...configs: Configuration[]): Configuration;

        /**
         * Merge multiple webpack configurations into one, with smart merging of loaders.
         */
        smart(...configs: Configuration[]): Configuration;
    }

    const merge: WebpackMerge;
    export = merge;
}
